.github/workflows/unit_tests.yml
requirements/requirements.txt
requirements/test_requirements.txt
tests/api_method_tests.py

Lock ovos_plugin_manager version for module compat.
spec HolmesV version in test_requirements to fix resolver errors

Fix dependency resolution

---

neon_audio/__main__.py

Fix logic error in server compat fix

---

neon_audio/tts/__init__.py

Refactor imports to use neon_utils and ovos_utils rather than mycroft where possible
Remove default mimic/mimic2 TTS engine imports (should always use plugin versions)

Refactor imports

---

.github/workflows/unit_tests.yml
neon_audio/tts/__init__.py
requirements/test_requirements.txt
tests/__init__.py
tests/test_objects/__init__.py
tests/unit_tests.py

Add unit tests of TTS class with dummy plugin

---

Dockerfile
requirements/docker.txt
setup.py

Move docker dependencies to docker.txt
Change docker dep from HolmesV to ovos-core to resolve build errors

Update docker dependencies

---

neon_audio/speech.py

Refactor Metrics handling to use neon_utils

---

neon_audio/__init__.py
neon_audio/__main__.py
neon_audio/speech.py
requirements/requirements.txt

Add call to init_config_dir
Update dependencies
Cleanup imports
Refactor global config init

Add one-time config initialization

---

neon_audio/speech.py

Remove mimic fallbackTTS deprecated in ovos-core 0.0.2

Deprecate fallbackTTS

---

.github/workflows/unit_tests.yml
requirements/docker.txt

Update Docker dependency specs
Add unit tests for PyPI and Docker builds

Fix docker dependency versions and add unit tests

---

Dockerfile
neon_audio/__main__.py
neon_audio/tts/__init__.py
requirements/docker.txt

Better default TTS value handling
Cleanup `execute` method
Add encoded audio files to klat responses

Minor bugfixes and klat.response changes

---

.github/workflows/license_tests.yml
requirements/requirements.txt
tests/license_tests.py

add license tests and workflow

---

.github/workflows/unit_tests.yml
Dockerfile
neon_audio/__main__.py
neon_audio/speech.py
neon_audio/tts/neon.py
requirements/docker.txt
requirements/requirements.txt
tests/license_tests.py

Minor logging changes
Add back TTS audio caching
Update dependencies to stable versions

Logging, Caching, Dependency Update

---

neon_audio/__init__.py
neon_audio/__main__.py
neon_audio/speech.py
requirements/docker.txt
requirements/requirements.txt

Fix signal method init in module start

---

neon_audio/__main__.py
neon_audio/service.py
requirements/requirements.txt

Handle config arg name change
Add TTS request logging

Kubernetes config fix

---

neon_audio/service.py
tests/api_method_tests.py

Add unit tests for message destination override

Fix default message routing handling

---

neon_audio/tts/neon.py
tests/unit_tests.py

Update klat.response handling to emit response if `klat_data` context is present (even if not True)
Add unit test cases for klat.response

Update klat.resposne handling

---

docker_overlay/etc/OpenVoiceOS/ovos.conf
neon_audio/service.py
requirements/requirements.txt
tests/api_method_tests.py

Add neon.get_languages_tts event handler with unit test
Update Docker ovos config

Add bus API method to get supported languages with unit test

---

.github/workflows/publish_release.yml
.github/workflows/publish_test_build.yml
neon_audio/__main__.py
neon_audio/service.py
neon_audio/tts/__init__.py
neon_audio/tts/neon.py
neon_audio/utils.py
requirements/requirements.txt
tests/license_tests.py

Update log references to ovos_utils
Init 'audio' log on module start
Update PyPI action references

Update log handling

---

Dockerfile
requirements/docker.txt
requirements/requirements.txt

Add `libsox-fmt-mp3` to docker deps for mp3 playback support

Update dependencies to stable versions

---

Dockerfile

**This should only be used temporarily and is not a real fix. Fix this before the next stable release**

Patch mimic build to allow insecure mycroft-desktop apt repo

---

Dockerfile

Revert patching around expired Mimic repo key

---

neon_audio/service.py
requirements/test_requirements.txt
tests/api_method_tests.py

Update unit tests to use FakeBus and handle more API test cases

Prevent waiting for unidentified speech to finish

---

.github/workflows/license_tests.yml
.github/workflows/publish_release.yml
.github/workflows/publish_test_build.yml
.github/workflows/pull_master.yml

Equivalent to https://github.com/NeonGeckoCom/neon_speech/pull/124
Before merging to `master` workflows should be updated to use default branch

Update workflows to use shared files

---

.github/workflows/license_tests.yml
.github/workflows/publish_release.yml
.github/workflows/publish_test_build.yml
.github/workflows/pull_master.yml
.github/workflows/unit_tests.yml

Updates automation references to default `master` branch
#109

Update automation references to `master` branch

---

requirements/requirements.txt

Updates OCP dependency to latest (alpha) version with all stream extractors
https://github.com/NeonGeckoCom/NeonCore/discussions/334#discussioncomment-5080001

Update OCP dependency to resolve news skill bug

---

.github/workflows/publish_test_build.yml
requirements/requirements.txt

Update automation to publish prereleases
Update stable dependencies

Add prerelease automation and update dependencies

---

.github/workflows/publish_test_build.yml

Fix release automation
Fix typo from #121

Fix alpha release automation change

---

requirements/requirements.txt

Updates OVOS Common Play plugin to stable release version

Update OCP plugin to stable version

---

.github/workflows/propose_release.yml

Adds action to propose a stable release
Missed in #121 and #122

Add missing release action

---

neon_audio/__main__.py
neon_audio/cli.py
neon_audio/service.py
neon_audio/tts/neon.py
requirements/requirements.txt
tests/api_method_tests.py
tests/unit_tests.py

Refactor to import from ovos-audio
Refactor mycroft-messagebus-client to ovos-bus-client

Refactor for ovos-audio compat.

---

neon_audio/__main__.py
requirements/requirements.txt

If `debug` is set in configuration, enable malloc tracing and logging

Add malloc debugging support

---

neon_audio/cli.py

Fix missed refactoring in CLI entrypoints

---

tests/unit_tests.py

Implement tests for CLI module

---

neon_audio/__main__.py
setup.py

Mark old CLI entrypoint as deprecated

---

Dockerfile

Add docker default `XDG_CONFIG_HOME` for k8s compat.

Update Dockerfile for Kubernetes

---

neon_audio/service.py
neon_audio/tts/neon.py
requirements/requirements.txt

Update `speaker` context handling to use safe references (partial fix for incompatible plugins)
Update `speak` message handling to use `Message.data['lang']` instead of hard-coded default Updated logging and dependencies

Improved language support and plugin compatibility

---

neon_audio/service.py
neon_audio/tts/neon.py

Adds more metrics context
Updates queue handling for ovos-audio compat.
https://github.com/NeonGeckoCom/neon-minerva/pull/3

Timing metrics and ovos-audio compat

---

requirements/requirements.txt

Pin ovos-plugin-manager to keep compatible combination of dependencies
https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/179

Pin upper limit to ovos-plugin-manager to work around breaking change

---

neon_audio/__main__.py
neon_audio/service.py
neon_audio/tts/neon.py
requirements/requirements.txt
tests/api_method_tests.py
tests/unit_tests.py

Update `speak_ident` handling for ovos-audio session refactor compat.
Update PlaybackThread for ovos-audio compat.
Refactor imports
Update dependencies

ovos-audio compatibility updates

---

requirements/requirements.txt

Loosen ovos-utils dependency spec to troubleshoot core module compat.
https://github.com/NeonGeckoCom/NeonCore/actions/runs/6503031714/job/17662928592?pr=563

Update dependencies for module compat.

---

requirements/requirements.txt

Update ovos-audio and ovos-plugin-manager dependencies to test latest alpha versions
Remove dependency patching now handled in ovos-audio

Update dependencies to test for stable releases

---

requirements/requirements.txt

Update to stable dependencies
Pin latest ovos-audio alpha dependency

Update dependencies to prep for stable release

---

neon_audio/tts/neon.py

Fix check to make sure Playback thread is started once and only once
Add specific exception handling for trying to start a thread more than once

Fix typo in thread state check

---

requirements/requirements.txt

Update OCP to pinned alpha version to resolve missing `mycroft-messagebus-client` dependency

Update OCP to latest alpha to resolve dependency error

---

neon_audio/tts/neon.py

Handle playback thread init bug affecting Docker instances

---

neon_audio/service.py
neon_audio/tts/neon.py
requirements/requirements.txt

Emit full local and klat interaction timing metrics
Update tts stopwatch to enable reporting

Send utterance metrics for PHAL plugin

---

neon_audio/tts/neon.py

Prevent exceptions on invalid metrics values

Handle invalid timing metrics

---

requirements/requirements.txt

Update neon-utils dependency to stable release

---

requirements/requirements.txt

Update ovos-audio to remove excessive empty log

---

requirements/requirements.txt

Unpins ovos-audio and ocp dependencies

Allow ovos-audio and OCP newer alpha releases

---

requirements/requirements.txt

Update OCP dependency to stable spec

---

.github/workflows/license_tests.yml

Run license tests on PR to `master`
Closes #128

Update license tests automation

---

requirements/requirements.txt

https://github.com/NeonGeckoCom/NeonCore/pull/708

Update requirements to allow latest OVOS packages

---

.github/workflows/license_tests.yml
.github/workflows/unit_tests.yml
LICENSE.md
docker_overlay/root/run.sh
neon_audio/__init__.py
neon_audio/__main__.py
neon_audio/cli.py
neon_audio/service.py
neon_audio/tts/__init__.py
neon_audio/tts/neon.py
neon_audio/utils.py
requirements/requirements.txt
setup.py
tests/__init__.py
tests/api_method_tests.py
tests/test_objects/__init__.py
tests/unit_tests.py
version.py

Update cli module to set default envvars
Remove references to deprecated `init_config_dir` function
Update Python versions used in unit tests
Update license notices for 2025
Patch `lang` handling for backwards-compat.

Update CLI configuration handling and unit tests

---

Dockerfile
neon_audio/__main__.py

Deprecate `PIDLock` initialization
Resolve Dockerfile warnings

Deprecate `PIDLock` usage and update Dockerfile to resolve warnings

---

.gitignore
docker_overlay/etc/neon/neon.yaml
neon_audio/utils.py
requirements/requirements.txt

Update requirements to support newer stable OVOS dependencies
Update gitignore
Update default Docker config
Fix incorrect type annotation

Update Docker config, dependencies

---

.github/workflows/unit_tests.yml
.github/workflows/update_docker_images.yml
requirements/requirements.txt

Add Python 3.12 unit tests
Add GHA to manually update Docker images
Update requirements to stable versions 
Add `ovos-audio-plugin-simple` dependency to resolve warnings

Update GHA and requirements

---

neon_audio/service.py

Remove invalid `speak` listener removal/re-addition

Resolve logged warning at init

---

neon_audio/tts/neon.py
requirements/docker.txt
requirements/test_requirements.txt

Update _get_tts deprecation warning so it exists in one stable release (internal method, so it does not break semver)
Update dependencies to stable versions

Update log and dependencies for stable release
